use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use solana_sdk::pubkey::Pubkey; // Keep for future use in specific models if needed, or remove if strictly following lints

/// A single price update for a symbol.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tick {
    pub symbol: String,
    pub price: f64,
    pub volume: f64,
    pub timestamp: DateTime<Utc>,
}

/// A level in the orderbook.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PriceLevel {
    pub price: f64,
    pub size: f64,
}

/// A snapshot or incremental update of an orderbook.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderbookUpdate {
    pub symbol: String,
    pub bids: Vec<PriceLevel>,
    pub asks: Vec<PriceLevel>,
    pub timestamp: DateTime<Utc>,
    pub seq_num: u64,
}

/// A trade event from the market.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    pub symbol: String,
    pub price: f64,
    pub size: f64,
    pub side: Side,
    pub timestamp: DateTime<Utc>,
}

/// Trading side.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Side {
    Buy,
    Sell,
}

/// A signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub strategy_id: String,
    pub symbol: String,
    pub action: Action,
    pub timestamp: DateTime<Utc>,
}

/// Action to be taken by the execution engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Action {
    CreateOrder(OrderParams),
    CancelOrder(String), // Order ID
    UpdateOrder(String, OrderParams),
}

/// Parameters for creating a new order.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderParams {
    pub side: Side,
    pub order_type: OrderType,
    pub price: Option<f64>,
    pub size: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderType {
    Limit,
    Market,
    IOC, // Immediate or Cancel
}

/// Event indicating a fill of our own order.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FillEvent {
    pub order_id: String,
    pub symbol: String,
    pub price: f64,
    pub size: f64,
    pub fee: f64,
    pub timestamp: DateTime<Utc>,
}

/// Update on the status of our order.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderStatusUpdate {
    pub order_id: String,
    pub status: OrderStatus,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderStatus {
    Pending,
    Open,
    Filled,
    PartiallyFilled,
    Cancelled,
    Rejected,
}
